package com.lttclaw.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ACCOUNT.
 */
public class account {

    private Long id;
    private String category;
    private String imguri;
    private String provider;
    /** Not-null value. */
    private String uname;
    private String shadow;
    private java.util.Date setDate;

    public account() {
    }

    public account(Long id) {
        this.id = id;
    }

    public account(Long id, String category, String imguri, String provider, String uname, String shadow, java.util.Date setDate) {
        this.id = id;
        this.category = category;
        this.imguri = imguri;
        this.provider = provider;
        this.uname = uname;
        this.shadow = shadow;
        this.setDate = setDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getImguri() {
        return imguri;
    }

    public void setImguri(String imguri) {
        this.imguri = imguri;
    }

    public String getProvider() {
        return provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

    /** Not-null value. */
    public String getUname() {
        return uname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUname(String uname) {
        this.uname = uname;
    }

    public String getShadow() {
        return shadow;
    }

    public void setShadow(String shadow) {
        this.shadow = shadow;
    }

    public java.util.Date getSetDate() {
        return setDate;
    }

    public void setSetDate(java.util.Date setDate) {
        this.setDate = setDate;
    }

}
