package com.lttclaw.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.lttclaw.greendao.account;

import com.lttclaw.greendao.accountDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountDaoConfig;

    private final accountDao accountDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountDaoConfig = daoConfigMap.get(accountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        accountDao = new accountDao(accountDaoConfig, this);

        registerDao(account.class, accountDao);
    }
    
    public void clear() {
        accountDaoConfig.getIdentityScope().clear();
    }

    public accountDao getAccountDao() {
        return accountDao;
    }

}
